# Generated by Django 5.0.7 on 2026-08-14 02:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('review_verified', 'Review Verified'), ('review_rejected', 'Review Rejected'), ('review_needs_info', 'Review Needs More Information'), ('review_published_unverified', 'Review Published Without Verification'), ('report_received', 'Report Received'), ('general', 'General')], default='general', max_length=40)),
                ('message', models.CharField(max_length=255)),
                ('related_review_id', models.UUIDField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
