# Generated by Django 5.0.7 on 2026-08-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('review_verified', 'Review Verified'), ('review_rejected', 'Review Rejected'), ('review_needs_info', 'Review Needs More Information'), ('review_published_unverified', 'Review Published Without Verification'), ('general', 'General')], default='general', max_length=40),
        ),
    ]
