# Generated by Django 5.0.7 on 2026-08-14 02:05

import django.core.validators
import django.db.models.deletion
import reviews.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(default=reviews.models.generate_reference_id, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(max_length=4000)),
                ('pros', models.TextField(blank=True, max_length=1000)),
                ('cons', models.TextField(blank=True, max_length=1000)),
                ('would_recommend', models.BooleanField(null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('service_date', models.DateField(help_text='When the reviewed service was used.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Verification'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_info', 'Needs More Information'), ('published_unverified', 'Published Without Verification')], default='pending', max_length=24)),
                ('allow_privacy_safe_indicator', models.BooleanField(default=True, help_text="User consent to show a 'Proof Verified' indicator (never the file itself).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=reviews.models.proof_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('transparency', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_for_money', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('response_time', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('fake', 'Fake review'), ('spam', 'Spam'), ('offensive', 'Offensive content'), ('misleading', 'Misleading information'), ('personal_info', 'Personal information'), ('duplicate', 'Duplicate review'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_info', 'Needs More Information'), ('published_unverified', 'Published Without Verification')], max_length=24)),
                ('checklist', models.JSONField(blank=True, default=dict, help_text="e.g. {'proof_relevant': true, 'matches_service': true, 'no_sensitive_info': true, 'no_spam': true, 'no_duplicate': true}")),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('internal_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_decisions', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='reviews.review')),
            ],
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['service', 'status'], name='reviews_rev_service_8ca24c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status', '-created_at'], name='reviews_rev_status_70a1f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'service', 'service_date'), name='one_review_per_user_service_date'),
        ),
        migrations.AddConstraint(
            model_name='helpfulvote',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='one_helpful_vote_per_user_per_review'),
        ),
        migrations.AddConstraint(
            model_name='reviewreport',
            constraint=models.UniqueConstraint(fields=('review', 'reporter'), name='one_report_per_user_per_review'),
        ),
    ]
