# Generated by Django 5.0.7 on 2026-08-15 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='helpfulvote',
            name='one_helpful_vote_per_user_per_review',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='one_review_per_user_service_date',
        ),
        migrations.RemoveConstraint(
            model_name='reviewreport',
            name='one_report_per_user_per_review',
        ),
        migrations.AddField(
            model_name='helpfulvote',
            name='anonymous_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='review',
            name='anonymous_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='review',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('te', 'Telugu'), ('mixed', 'Mixed')], default='en', help_text='Language the reviewer wrote in — informational only, never translated or altered.', max_length=8),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, help_text='Display name for logged-out submissions. Ignored if is_anonymous is set.', max_length=80),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='anonymous_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='helpfulvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpful_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='helpfulvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('review', 'user'), name='one_helpful_vote_per_user_per_review'),
        ),
        migrations.AddConstraint(
            model_name='helpfulvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('anonymous_id', ''), _negated=True)), fields=('review', 'anonymous_id'), name='one_helpful_vote_per_anon_per_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'service', 'service_date'), name='one_review_per_user_service_date'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('anonymous_id', ''), _negated=True)), fields=('anonymous_id', 'service', 'service_date'), name='one_review_per_anon_service_date'),
        ),
        migrations.AddConstraint(
            model_name='reviewreport',
            constraint=models.UniqueConstraint(condition=models.Q(('reporter__isnull', False)), fields=('review', 'reporter'), name='one_report_per_user_per_review'),
        ),
        migrations.AddConstraint(
            model_name='reviewreport',
            constraint=models.UniqueConstraint(condition=models.Q(('reporter__isnull', True), models.Q(('anonymous_id', ''), _negated=True)), fields=('review', 'anonymous_id'), name='one_report_per_anon_per_review'),
        ),
    ]
