# Generated by Django 5.0.7 on 2026-08-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_helpfulvote_one_helpful_vote_per_user_per_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewproof',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='proof-previews/'),
        ),
    ]
