# Generated by Django 5.0.7 on 2026-08-24 17:46

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewproof_preview_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewproof',
            name='preview_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reviewproof',
            name='preview_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reviewproof',
            name='preview_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewproof',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to=reviews.models.proof_preview_upload_path),
        ),
    ]
