# Generated by Django 5.0.7 on 2026-08-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions'), ('disclaimer', 'Disclaimer'), ('about', 'About Us'), ('contact', 'Contact Us'), ('review_policy', 'Review Policy')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page_type'],
            },
        ),
    ]
